/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./src/components/ui/UiButton.vue')['default']
    UiCheckBox: typeof import('./src/components/ui/UiCheckBox.vue')['default']
    UiIcon: typeof import('./src/components/ui/UiIcon.vue')['default']
    UiInput: typeof import('./src/components/ui/UiInput.vue')['default']
    UiPagination: typeof import('./src/components/ui/UiPagination.vue')['default']
    UiSelect: typeof import('./src/components/ui/UiSelect.vue')['default']
    UiSideLink: typeof import('./src/components/ui/UiSideLink.vue')['default']
  }
}
